[project]
name = "grievance-redressal"
version = "0.0.1"
description = "A basic grievance-redressal management system."
dependencies = [
    "Flask", "Flask-Mail", "pyotp", "python-dotenv",
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"
